//#########################################################################
//--------------------------------COMMANDS---------------------------------

DEF_CMD (PUSH,   0x01)
DEF_CMD (POP,    0x02)
DEF_CMD (JMP,    0x03)
DEF_CMD (ADD,    0x04)
DEF_CMD (SUB,    0x05)
DEF_CMD (MOD,    0x00)
DEF_CMD (MUL,    0x06)
DEF_CMD (DIV,    0x07)
DEF_CMD (SIN,    0x08)
DEF_CMD (COS,    0x09)
DEF_CMD (SQRT,   0x0A)
DEF_CMD (NEG,    0x0B)
DEF_CMD (OUT,    0x0C)
DEF_CMD (IN,     0x0D)
DEF_CMD (DUMP,   0x0E)
DEF_CMD (HLT,    0x0F)
DEF_CMD (CA,     0x19)
DEF_CMD (CAE,    0x1A)
DEF_CMD (CB,     0x1B)
DEF_CMD (CBE,    0x1C)
DEF_CMD (CE,     0x1D)
DEF_CMD (CNE,    0x1E)
DEF_CMD (JA,     0x10)
DEF_CMD (JAE,    0x11)
DEF_CMD (JB,     0x12)
DEF_CMD (JBE,    0x13)
DEF_CMD (JE,     0x14)
DEF_CMD (JNE,    0x15)
DEF_CMD (CALL,   0x16)
DEF_CMD (RETURN, 0x17)
DEF_CMD (SHOW,   0x18)
DEF_CMD (DRAW,   0x1F)