
OPERATION(FLD,        "fld"              )
OPERATION(FST,        "fstp"             )
OPERATION(PUSH,       "push"             )
//OPERATION(MOV,        "mov"              )
OPERATION(POP,        "pop"              )
OPERATION(SUB,        "sub"              )
OPERATION(ADD,        "add"              )
OPERATION(IN,         "call _stdlib_in_" )
OPERATION(OUT,        "call _stdlib_out_")
OPERATION(HLT,        "call _stdlib_hlt_")
OPERATION(FCOMPP,     "fcompp"           )
OPERATION(FSTSW,      "fstsw"            )
OPERATION(SAHF,       "sahf"             )
OPERATION(RETURN,     "ret"              )


ARITHMETIC_OP(FADD, "fadd")
ARITHMETIC_OP(FSUB, "fsub")
ARITHMETIC_OP(FMUL, "fmul")
ARITHMETIC_OP(FDIV, "fdiv")
ARITHMETIC_OP(FCHS, "fchs")
ARITHMETIC_OP(FSQRT,"fsqrt")


REGISTER(AX,   1,  "ax" )
REGISTER(RAX,  2,  "rax")
REGISTER(RBX, 'a', "rbx")
REGISTER(RCX, 'b', "rcx")
REGISTER(RDX, 'c', "rdx")
REGISTER(RSP,  3,  "rsp")
REGISTER(RSI, 'd', "rsi")

JUMP_OP (JMP,  "jmp" )
JUMP_OP (CALL, "call")
JUMP_OP (JA,   "ja"  )
JUMP_OP (JAE,  "jae" )
JUMP_OP (JB,   "jb"  )
JUMP_OP (JBE,  "jbe" )
JUMP_OP (JE,   "je"  )
JUMP_OP (JNE,  "jne" )
