//#########################################################################
//--------------------------------COMMANDS---------------------------------

DEF_CMD (PUSH,   0x01)
DEF_CMD (POP,    0x02)
DEF_CMD (JMP,    0x03)
DEF_CMD (ADD,    0x04)
DEF_CMD (SUB,    0x05)
DEF_CMD (MUL,    0x06)
DEF_CMD (DIV,    0x07)
DEF_CMD (OUT,    0x0C)
DEF_CMD (IN,     0x0D)
DEF_CMD (HLT,    0x0F)
DEF_CMD (JA,     0x10)
DEF_CMD (JAE,    0x11)
DEF_CMD (JB,     0x12)
DEF_CMD (JBE,    0x13)
DEF_CMD (JE,     0x14)
DEF_CMD (JNE,    0x15)
DEF_CMD (CALL,   0x16)
DEF_CMD (NEG,    0x0B)
DEF_CMD (RETURN, 0x17)